### ISSUE TITLE
[Question] jToolBar utils buttons behavior

### ISSUE THREAD

**Issue by vincenzopalazzo** [argouml-tigris-org/argouml#12]
Hi @linustolke,

I'm opening this issue because I want to make some questions about the behaviors on Jtoolbar utils.

I'm making the last tests with ArgoUML before starting to write the code to integrate [material-ui-swing](https://github.com/vincenzopalazzo/material-ui-swing) and I noted this behavior in the video below.

![](https://media.giphy.com/media/XaAXcq7frEdVeUY8dq/giphy.gif)

Before making the questions, I want say that the mouse hover in the L&F library has a timer to implement the mouse hover effect, this timer changes the background during life, but before finishing, it reset the original color to the component.

*Question*

I noted this behavior only on this Jtoolbar, I want ask a question about what happened inside the code when I clicked on the button in this JToolBar? 
Can you explane me or link the code? Maybe I have an bug inside the mousehover effect.

Thanks for your time.

**Comment by linustolke** [comment]
I am not the right person to answer this. I don't know any details on swing, jtoolbar, and the other involved libraries. Hopefully somebody else can help you.

**Comment by vincenzopalazzo** [comment]
Hi @linustolke,

I found the "problem", the button in the Jtool bars is a personal button and with some L&F the button doesn't change the status alone but the client in this case should be writing the code to set the status of the button to unselect. This work in Material-UI-Swing was done by the mouse hover event and for this reason, I see the strange effect on the Toolbar, I will try to support this change inside the library.
The reference of the code is [here](https://github.com/argouml-tigris-org/argouml/blob/b8cb3e1c156bdf47f8f604a7c23c88df62b6b43b/src/argouml-app/src/org/argouml/uml/diagram/ui/UMLDiagram.java#L433)

I'm closing the issue because I discovered the answer
