### ISSUE TITLE
Tests are failing when running with coverage

### ISSUE THREAD

**Issue by linustolke** [argouml-tigris-org/argouml#2]
I have fixed the tests so that `mvn test` now shows no failing tests.

However, `mvn cobertura:cobertura`, running the same tests, fails for some of them. This means that the coverage result reported is not the actual coverage result from running the tests.

To solve this I guess knowledge of how the cobertura plugin and mvn configuration works.

**Comment by alepekhin** [comment]
Works for me with maven 3.6 and Java 8

**Comment by linustolke** [comment]
This is now resolved with the settings for the jacoco plugin you provided.
