### ISSUE TITLE
The tigris.org domain is defunct yet much of argoUML refers to it

### ISSUE THREAD

**Issue by marlowa** [argouml-tigris-org/argouml#3]
tigris.org has been shutdown but the resources section of https://github.com/argouml-tigris-org/argouml still refers to it, and the repo URL in the 'contributing' section.

**Comment by linustolke** [comment]
OK. The contributing section is probably just the tip of the iceberg. There are some libraries that the maven build relies upon that where in argouml-downloads.tigris.org.

**Comment by linustolke** [comment]
I just tested and the site seems to be up with a message. We probably have a few days more.

**Comment by linustolke** [comment]
Thanks!

Is this update in the right direction?
https://review.gerrithub.io/c/argouml-tigris-org/argouml/+/487638

Mvh
Linus

Den sön 15 mars 2020 kl 12:51 skrev Andrew Peter Marlow <
notifications@github.com>:

**Comment by marlowa** [comment]
> Thanks! Is this update in the right direction? https://review.gerrithub.io/c/argouml-tigris-org/argouml/+/487638 Mvh Linus Den sön 15 mars 2020 kl 12:51 skrev Andrew Peter Marlow < notifications@github.com>:
> […](#)
> tigris.org has been shutdown but the resources section of https://github.com/argouml-tigris-org/argouml still refers to it, and the repo URL in the 'contributing' section. 

This is looking better, thanks.

**Comment by linustolke** [comment]
I have now gone through the rest of the projects and fixed the issues, web browser access, anonymous access and the developeraccess. You can examine the changes at [Gerrithub](https://review.gerrithub.io/q/argouml-tigris-org+is:open). I will have another look at the changes and approve when the verification is done.

**Comment by linustolke** [comment]
I noticed afterwards that there is a maven warning in most other projects (when building site). This is because I tried to rely on the parentpom instead of being explicit. I will have to revisit that.

**Comment by linustolke** [comment]
README.md is handled in #8.

**Comment by linustolke** [comment]
> I noticed afterwards that there is a maven warning in most other projects (when building site). This is because I tried to rely on the parentpom instead of being explicit. I will have to revisit that.

On second thought, I will consider this one fixed and do the fixing up of the pom files later.
