### ISSUE TITLE
`repo upload` failed for me, even though I have an account on gerrit

### ISSUE THREAD

**Issue by linustolke** [argouml-tigris-org/argouml#32]
Hello @stcarrez!

You wrote:
[...] 
I was able to use `repo` as explained, build, test and so on, but the submission with `repo upload` failed for me, even though I have an account on gerrit.
[...]
_Originally posted by @stcarrez in https://github.com/argouml-tigris-org/argouml/issues/9#issuecomment-657004688_

I would like us to solve this. Could you provide some details like the command you are using and the error messages you get?

**Comment by linustolke** [comment]
Hello again @stcarrez !
I have now understood more about the access rights in Gerrit and modified so that it should be possible for you and all other logged in users, to push changes to the argouml project. Please try it and let me know if it works.

Thanks for pointing this out.

**Comment by stcarrez** [comment]
Ok, thanks.

Now the repo thing is a nightmare and at work I've managed to remove it. I don't have time to spend in using gerrit.

**Comment by linustolke** [comment]
OK. I will assume that it is working then since you don't have time to verify it.
