### ISSUE TITLE
how to add plugin

### ISSUE THREAD

**Issue by alepekhin** [argouml-tigris-org/argouml#46]
Can you tell me how I can add argouml-db plugin to main argouml app?

**Comment by euluis** [comment]
Add the argouml_db.jar to the ext subdir in the ArgoUML installation directory. All the plugins as well as the i18n modules' jars go in there.

**Comment by euluis** [comment]
The answer was replied if it resolves the problem, please close the issue.

**Comment by alepekhin** [comment]
yes, thank you, it works
