### ISSUE TITLE
died link in readme

### ISSUE THREAD

**Issue by vincenzopalazzo** [argouml-tigris-org/argouml#8]
Hi all,

I'm reading the readme and I noted that this link is died http://argouml.tigris.org/wiki/Working_with_git%2C_github%2C_gerrit%2C_gerrithub_and_repo

**Comment by linustolke** [comment]
Thanks. This is now fixed. I also removed the link in the organization.
This page had an older and not updated version of the contents in https://github.com/argouml-tigris-org/argouml/wiki . The old version of the page is available from https://argouml-tigris-org.github.io/tigris/wiki-argouml/wiki/Working_with_git,_github,_gerrit,_gerrithub_and_repo.html
